//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiPlagiarism.Vsix {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VSIXResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VSIXResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntiPlagiarism.Vsix.Resources.VSIXResource", typeof(VSIXResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison with Acumatica sources provided with Acumatica ERP.
        /// </summary>
        public static string AcumaticaSourcesWorkModeDescription {
            get {
                return ResourceManager.GetString("AcumaticaSourcesWorkModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acumatica Sources.
        /// </summary>
        public static string AcumaticaSourcesWorkModeTitle {
            get {
                return ResourceManager.GetString("AcumaticaSourcesWorkModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AntiPlagiarism.
        /// </summary>
        public static string AntiPlagiarismWindowTitle {
            get {
                return ResourceManager.GetString("AntiPlagiarismWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use current solution as a source for comparison.
        /// </summary>
        public static string CurrentSolutionSourceOriginDescription {
            get {
                return ResourceManager.GetString("CurrentSolutionSourceOriginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Solution.
        /// </summary>
        public static string CurrentSolutionSourceOriginTitle {
            get {
                return ResourceManager.GetString("CurrentSolutionSourceOriginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison with selected reference solution.
        /// </summary>
        public static string ReferenceSolutionWorkModeDescription {
            get {
                return ResourceManager.GetString("ReferenceSolutionWorkModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Solution.
        /// </summary>
        public static string ReferenceSolutionWorkModeTitle {
            get {
                return ResourceManager.GetString("ReferenceSolutionWorkModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use selected folder as a source for comparison.
        /// </summary>
        public static string SelectedFolderSourceOriginDescription {
            get {
                return ResourceManager.GetString("SelectedFolderSourceOriginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Folder.
        /// </summary>
        public static string SelectedFolderSourceOriginTitle {
            get {
                return ResourceManager.GetString("SelectedFolderSourceOriginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use selected project as a source for comparison.
        /// </summary>
        public static string SelectedProjectSourceOriginDescription {
            get {
                return ResourceManager.GetString("SelectedProjectSourceOriginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Project.
        /// </summary>
        public static string SelectedProjectSourceOriginTitle {
            get {
                return ResourceManager.GetString("SelectedProjectSourceOriginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare solution with itself to find possibilities for refactoring.
        /// </summary>
        public static string SelfAnalysisWorkModeDescription {
            get {
                return ResourceManager.GetString("SelfAnalysisWorkModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-Analysis.
        /// </summary>
        public static string SelfAnalysisWorkModeTitle {
            get {
                return ResourceManager.GetString("SelfAnalysisWorkModeTitle", resourceCulture);
            }
        }
    }
}
